config/routes.rb
Rails.application.routes.draw do
  resources :shows
  get 'home/index'

  resources :about
  get 'about/index'
  get 'about', to: 'about#index'

  resources :donate
  get 'donate/index'
  get 'donate', to: 'donate#index'

  root 'home#index'

end

app/models/show.rb
class Show < ActiveRecord::Base
	validates :title, presence: true, length: { maximum: 70 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:title, :description, :guest_name, :youtubeID, :gender, 
                                   :age, :zip, :current_religion, :religious_heritage)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shows_helper.rb
module ShowsHelper

	def gender_options
		I18n.t(:gender_options).map { |key, value| [ value, key ] } 
	end

	def religion_options
		I18n.t(:religion_options).map { |key, value| [ value, key ] } 
	end

end

app/views/about/index.html.erb
<!--  ///////////////////     Interview Panels     //////////////////-->
  <div class="profile-header text-center" style="background-color: #222222; background-image: url(<%= asset_path 'ep5_karl-parker.jpg' %>); background-size: 100% auto; background-repeat: no-repeat;">
    <div class="container-fluid">
      <div class="container-inner">
        <h3 class="profile-header-user">Over Coffee</h3>
        <p class="profile-header-bio">A 30-minute weekly online tv show where Rev. Dave intervews his guests
                                        about their spiritual stories.</p>
      </div>
    </div>
    <nav class="profile-header-nav">
      <ul class="nav nav-tabs">
        <li class="active"><%= link_to("About", :controller => "about") %></li>
      </ul>
    </nav>
  </div>
  <div class="m-t" style="margin-bottom: 50px">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default panel-profile" style="padding: 20px; margin-top: 40px">
        <%= link_to image_tag("oc_logo_200px.png", 
                                :alt => "Over Coffee with Rev. Dave Thompson",
                                :class => "panel-profile-img center-block"),
              root_path %>
        <h4>Why did I create this show?</h4>
        <p>This whole project came about from a question that has caused an ongoing internal struggle for me...In our global community, how do we learn to peacefully live together with fundamental differences in how we view God, life, purpose, and morals?</p>

        <p>I decided to launch this show, as a program of <%= link_to "World Uniting", "http://www.worlduniting.org", :target => "_blank" %>, called Over Coffee where I could seek to address this very question head-on by listening to the spiritual stories of people from all walks of life and spirituality, in a casual setting over coffee.</p>

        <p>Each episode features a new guest. The interview is broken into three sections: (1) Spiritual heritage and early life, (2) Major life events that have shaped their spirituality, (3) and relevant issues with which they are currently engaging or wrestling.</p>

        <p>Each episode is filmed on location with a minimal studio setup, utilizing a GoPro wide-angle camera, H6 Digital Recorder with Mid-Side mic and lapels mix-down, and minimal box lighting as necessary.</p>

        <p>I do hope you enjoy this show. I have already learned so much. It has been an overwhelming honor to have my guests trust me to share their stories with you. Please do let me know if there are ways that you think I might improve the show, the questions I ask, or the way I part my hair.</p>

        <p>Rev. Dave</p>
        
        <%= image_tag "dave_signature.png" %>
        </div>
      </div>
    </div>
  </div>

app/views/donate/index.html.erb
<div class="well well-lg col-md-10 col-md-offset-1">
  <div class="row">
      <div class="panel panel-default panel-profile">
        <div class="panel-body text-center">
          <iframe src="https://donorbox.org/embed/over-coffee-with-rev-dave-thompson?show_content=true" height="685px" width="100%" style="max-width:100%; min-width:780px" seamless="seamless" name="donorbox" frameborder="0" scrolling="no"></iframe>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container p-t-md">
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default panel-profile m-b-md">
        <div class="panel-body text-center">
          <%= link_to image_tag("oc-magnet.png", 
                                :alt => "Over Coffee with Rev. Dave Thompson",
                                :class => "panel-profile-img",
                                :style => "-ms-transform: rotate(7deg); -webkit-transform: rotate(7deg); transform: rotate(7deg);"),
              root_path %>

          <h5 class="panel-title">
            Welcome<br>
          </h5>

          <p class="m-b-md">Over Coffee is a weekly Sunday morning TV show where Rev. Dave Thompson listens to the spiritual stories of everyday people.</p>

          <%= link_to button_tag("About the Show", :type => "button", :class => "btn btn-primary-outline btn-sm"), :controller => "about" %>
        </div>
      </div>
      <p>&nbsp;</p>


    </div>

    <div class="col-md-6">
      <ul class="list-group media-list media-list-stream">


        <li class="media list-group-item p-a">
        <%= link_to image_tag("this_sunday-magnet.png", 
                              :alt => "This Sunday 8am",
                              :class => "panel-profile-img center-block",
                              :style => "-ms-transform: rotate(-17deg); -webkit-transform: rotate(-17deg); transform: rotate(-17deg);"),
            "http://overcoffee.tv" %>
          <a class="media-left" href="#">
            <span class="icon icon-youtube"></span>
          </a>
          <div class="media-body">
            <div class="media-heading">
              <small class="pull-right text-muted">Sunday April 10, 2016</small>
              <h5>Over Coffee with Rev. Dave Thompson - Barbara Christwitz</h5>
              <h6>A Quaker & Methodist</h6>
            </div>

            <p><iframe width="80%" src="https://www.youtube.com/embed/WckcM6XZjJg" frameborder="0" allowfullscreen class="center-block"></iframe></p>
            <p>
              
              <strong>Spiritual Tags</strong>
              <%= link_to button_tag("Quaker", :type => "button", :title => "Quaker", :class => "btn btn-primary-outline btn-sm"), :controller => "home" %>
              <%= link_to button_tag("Methodist", :type => "button", :title => "Methodist", :class => "btn btn-primary-outline btn-sm"), :controller => "home" %>
            </p>
            <p>
              Barbara Christwitz of Clearlake, CA shares her spiritual story: early life in the American Midwest as a Methodist; later movement toward the Quaker community; and later circling-back-around to add the Methodist community to her spiritual communities.
            </p>

          </div>
        </li>
      </ul>

      
      <ul class="list-group media-list media-list-stream">


        <li class="media list-group-item p-a">
        <%= link_to image_tag("last-sunday-magnet.png", 
                              :alt => "Last Sunday 8am",
                              :class => "panel-profile-img center-block",
                              :style => "-ms-transform: rotate(17deg); -webkit-transform: rotate(17deg); transform: rotate(17deg);"),
            "http://overcoffee.tv" %>
          <a class="media-left" href="#">
            <span class="icon icon-youtube"></span>
          </a>
          <div class="media-body">
            <div class="media-heading">
              <small class="pull-right text-muted">Sunday April 3, 2016</small>
              <h5>Over Coffee with Rev. Dave Thompson - Carol Cole-Lewis</h5>
              <h6>Unitarian Universalist, Walnut Farmer &amp; Entrepreneur</h6>
            </div>

            <p><iframe width="80%" src="https://www.youtube.com/embed/Y_4S2j1WZ2U" frameborder="0" allowfullscreen class="center-block"></iframe></p>
            <p>
              
              <strong>Spiritual Tags</strong>
              <%= link_to button_tag("Unitarian", :type => "button", :title => "Christian", :class => "btn btn-primary-outline btn-sm"), :controller => "home" %>
            </p>
            <p>
              Carol, now a Unitarian Universalist, shares about her life in Manhattan, in London, and elsewhere abroad, as well as her new venture as a walnut farmer.
            </p>

          </div>
        </li>
      </ul>
      
      <ul class="list-group media-list media-list-stream">

        <li class="media list-group-item p-a">
          <%= link_to image_tag("previous-episodes-magnet.png", 
                                :alt => "Previous Episodes",
                                :class => "panel-profile-img center-block",
                              :style => "-ms-transform: rotate(-4deg); -webkit-transform: rotate(-4deg); transform: rotate(-4deg);"),
              "http://www.youtube.com/c/OvercoffeeTv", :target => "_blank" %>
          <div class="media-body">
            <div class="media-heading text-center">

              <p><strong>For more episodes, visit our</strong></p>
              <p><a href="http://www.youtube.com/c/OvercoffeeTv" target="_blank"><span class="icon icon-youtube"></span> YouTube Channel (OverCoffeeTv)</a></p>

            </div>
          </div>
        </li>

      </ul>
      
    </div>

    <div class="col-md-3">

      <div class="panel panel-default panel-profile m-b-md">
        <div class="panel-body text-center">
          <%= link_to image_tag("dave-magnet.png", 
                                  :alt => "Over Coffee with Rev. Dave Thompson", 
                                  :style => "-ms-transform: rotate(1deg); -webkit-transform: rotate(1deg); transform: rotate(1deg);",
                                  :class => "panel-profile-img center-block"),
                                "http://about.me/revdavethompson",
                                :target => "_blank" %>

          <h5 class="panel-title">
            <a class="text-inherit" href="profile/index.html">Rev. Dave Thompson</a>
          </h5>

          <ul class="list-unstyled list-spaced text-center">
              <li><span class="text-muted icon icon-calendar"></span> Make an <a href="https://www.calendly.com/revdave" target="_blank" title="Rev Dave's Calendar">Appointment</a></li>
              <li><span class="text-muted icon icon-facebook"></span> Connect on <a href="https://www.facebook.com/davethompsonpage" target="_blank" title="Rev Dave's Facebook">Facebook</a></li>
              <li><span class="text-muted icon icon-twitter"></span> Connect on <a href="http://twitter.com/revdavethompson" target="_blank" title="Rev Dave's Twitter">Twitter</a></li>
              <li><span class="text-muted icon icon-google-play"></span> Songs on <a href="https://play.google.com/store/music/album/D_a_Thompson_Disclaimer?id=Bkjlgjpday6f4k5cu6sehs6pkye" target="_blank" title="Rev Dave's Music">iTunes</a></li>
              <li><span class="text-muted icon icon-book"></span> Books on <a href="http://www.amazon.com/Over-Coffee-Conversation-Partnership-Conservative/dp/0983567735/ref=sr_1_1?ie=UTF8&qid=1441824909&sr=8-1&keywords=over+coffee" target="_blank" title="Rev Dave's Books on Amazon">Amazon</a></li>
              <li><span class="text-muted icon icon-github"></span> Software on <a href="https://github.com/worlduniting/" target="_blank" title="Rev Dave's Github">Github</a></li>
          </ul>

          <%= link_to button_tag("About Rev. Dave", :type => "button", :class => "btn btn-primary-outline btn-sm"), "http://revdavethompson.com", :target => "_blank" %>
        </div>

      </div>
      <p>&nbsp;</p>

      <div class="panel panel-default panel-link-list">
      <%= link_to image_tag("world-uniting-magnet.png", 
                              :alt => "World Uniting, Intl'", 
                              :style => "-ms-transform: rotate(-7deg); -webkit-transform: rotate(-7deg); transform: rotate(-7deg);",
                              :class => "panel-profile-img center-block"),
                            "http://worlduniting.org",
                            :target => "_blank" %>
        <div class="panel-body">
          
          © 2015 <a href="http://worlduniting.org" target="_blank">World Uniting, Intl'</a>

          <p>World Uniting’s mission is to promote peace by providing programs that facilitate empathy in order to learn how to love others whose world views may fundamentally conflict with our own.</p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- These meta tags come first. -->    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="imagetoolbar" content="no" />
    <meta http-equiv="content-script-type" content="text/javascript" />

    <!-- Basic Page info -->
    <title>Over Coffee with Rev. Dave Thompson</title>
    <meta name="description" content="Over Coffee is a weekly Sunday morning TV show where Rev. Dave Thompson listens to the spiritual stories of everyday people." />
    <meta keywords="Over Coffee, Rev. Dave Thompson, Coffee, Conversation, Religion, Faith, Interview, Celebrity, Spirituality, TV Series, TV Show, YouTube Channel, Sunday, Sunday Morning, Church" />
    <meta name="author" content="Rev. Dave Thompson" />
    <meta name="copyright" content="Copyright (c) 2015-2016 World Uniting, Intl, All rights reserved" />
    <meta name="company" content="World Uniting, Intl &mdash; Over Coffee TV" />
    <meta name="revisit-after" content="3 days" />

    <!-- Social Media Tags -->
    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="Over Coffee with Rev. Dave Thompson &mdash; What's Your Spiritual Story?">
    <meta itemprop="description" content="Over Coffee is a weekly Sunday morning TV show where Rev. Dave Thompson listens to the spiritual stories of everyday people.">
    <meta itemprop="image" content="<%= asset_path('oc-magnet.png') %>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@revdavethompson">
    <meta name="twitter:title" content="Over Coffee with Rev. Dave Thompson">
    <meta name="twitter:description" content="Over Coffee is a weekly Sunday morning TV show where Rev. Dave Thompson listens to the spiritual stories of everyday people.">
    <meta name="twitter:creator" content="@revdavethompson">
    <!-- Twitter summary card with large image must be at least 280x150px -->
    <meta name="twitter:image:src" content="<%= asset_path('oc-magnet.png') %>">

    <!-- Open Graph data -->
    <meta property="og:title" content="Over Coffee with Rev. Dave Thompson" />
    <meta property="og:description" content="Over Coffee is a weekly Sunday morning TV show where Rev. Dave Thompson listens to the spiritual stories of everyday people." />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://overcoffee.tv" />
    <meta property="og:image" content="<%= asset_path('oc-magnet.png') %>" />
    <meta property="og:site_name" content="Over Coffee TV" />
    <meta property="fb:admins" content="738483572" />
    <meta property="fb:app_id" content="405884566248725" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Facebook Thumbnail Image -->
    <link rel="image_src" href="<%= asset_path('oc-magnet.png') %>" />

    <!-- Include the CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Include JS -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- CSRF -->
    <%= csrf_meta_tags %>

    <!-- Include Open Sans font -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>

    <!-- Google mobile recommendations https://support.google.com/business/answer/4569085?p=link_page_to_website&rd=2 -->
    <link href="https://plus.google.com/+OvercoffeeTv" rel="publisher" />

    <!-- Favicons and touch icons -->
    <link href="<%= asset_path('favicon.png') %>" rel="shortcut icon" type="image/png"/>
    <link href="<%= asset_path('favicon.png') %>" rel="shortcut icon" type="image/x-icon"/>
    <link rel="icon" href="<%= asset_path('favicon.png') %>">

    <!-- Facebook Thumbnail Image -->
    <link rel="image_src" href="<%= asset_path('oc-magnet.png') %>" />

  </head>
  
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul class="nav navbar-nav">
            <li>
              <%= link_to("Home", root_path) %>
            </li>
            <li>
              <%= link_to("About the Show", :controller => "about") %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right m-r-0">
            <li>
              <%= link_to("Donate", :controller => "donate") %>
            </li>
          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

  	<%= yield %>


    <footer class="footer">
      <div class="text-muted text-center">
        <p>Over Coffee with Rev. Dave Thompson is a program of 
          <a href="http://worlduniting.org" target="_blank">World Uniting, Intl</a>.<br />
          &copy; World Uniting, Intl. All rights reserved.</p>
      </div>
    </footer>

    <script type="text/javascript" async defer
      src="https://apis.google.com/js/platform.js?publisherid=110400614747438521219">
    </script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-59712520-5', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :id => 'title_text', :size => 75 %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :cols => 75, :rows => 10 %>
  </div>
  <div class="form-group">
    <%= f.label :guest_name %><br>
    <%= f.text_field :guest_name, :size => 75 %>
  </div>
  <div class="form-group">
    <%= f.input :published_date, as: :date_picker, :label => 'Published Date',
                    input_html: {data: {date_options: {defaultDate: '2012/12/25'}}} %>
  </div>
  <div class="form-group">
    <%= f.label :youtubeID %><br>
    <%= f.text_field :youtubeID, :size => 75 %>
  </div>
  <div class="form-group">
    <%= f.label :gender %><br>
    <%= f.select :gender, gender_options, {}, {:class => "custom-select"} %>
  </div>
  <div class="form-group">
    <%= f.label :age %><br>
    <%= f.text_field :age, :size => 3 %>
  </div>
  <div class="form-group">
    <%= f.label :zip %><br>
    <%= f.text_field :zip, :size => 10 %>
  </div>
  <div class="form-group">
    <%= f.label :religious_heritage %><br>
    <%= f.select :religious_heritage, religion_options, {}, {:class => "custom-select"} %>
  </div>
  <div class="form-group">
    <%= f.label :current_religion %><br>
    <%= f.select :current_religion, religion_options, {}, {:class => "custom-select"} %>
  </div>
      <%= f.submit :class => "btn btn-default" %>
<% end %>

app/views/shows/edit.html.erb
<div class="well well-lg col-md-8 col-md-offset-2">

	<h1>Editing Show</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @show %> |
	<%= link_to 'Back', shows_path %>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
</div>

app/views/shows/index.html.erb
<div class="well well-lg col-md-10 col-md-offset-1">
  <p id="notice"><%= notice %></p>

  <h1>Show Listings</h1>
  <%= link_to 'New Show', new_show_path, :class => "pull-right" %>

  <table width="100%">
    <thead>
      <tr>
        <th>Guest</th>
        <th>Title</th>
        <th>Published Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @shows.each do |show| %>
        <tr class="<%= cycle('even', 'odd') -%>">
          <td><%= show.guest_name %></td>
          <td><%= show.title %></td>
          <td><%= show.published_date %></td>
          <td><%= link_to 'Show', show %></td>
          <td><%= link_to 'Edit', edit_show_path(show) %></td>
          <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  
</div>

app/views/shows/new.html.erb
<div class="well well-lg col-md-8 col-md-offset-2">
	<h1>New Show</h1>

	<%= render 'form' %>

	<%= link_to 'Back', shows_path %>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
</div>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @show.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @show.description %>
</p>

<p>
  <strong>Guest:</strong>
  <%= @show.guest_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @show.gender %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>